[feeluown-core]
src.pypi = "feeluown"
fetch.pypi = "feeluown"

[qliveplayer]
src.github = "IsoaSFlus/QLivePlayer"
fetch.github = "IsoaSFlus/QLivePlayer"
git.fetchSubmodules = true

[fcitx5-pinyin-zhwiki]
src.aur = "fcitx5-pinyin-zhwiki"
# $ver can be used in fetch.url
fetch.url = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.2.2/zhwiki-$ver.dict"

[apple-emoji]
# a fake version
src.manual = "0.0.0.20200413"
fetch.url = "https://github.com/samuelngs/apple-emoji-linux/releases/download/latest/AppleColorEmoji.ttf"

[nvfetcher-git]
# following the latest commit
src.git = "https://github.com/berberman/nvfetcher"
fetch.github = "berberman/nvfetcher"

[gcc-10]
# Find a tag by regex
src.github_tag = "gcc-mirror/gcc"
src.include_regex = "releases/gcc-10.*"
fetch.github = "gcc-mirror/gcc"

[vim]
src.webpage = "http://ftp.vim.org/pub/vim/patches/7.3/"
src.regex = "7\\.3\\.\\d+"
fetch.github = "vim/vim"
